### PR TITLE
Edits proposals

### PR DESCRIPTION
**Pull request by vanrein**
Hoping not to rake up past discussions, here are a few suggestions for change.  Each change is in a separate commit, to allow for cherry picking.

### CODE REVIEW

**Comment by oej** [comment]
THanks! We'll take a look and process this.

**Comment by vanrein** [comment]
I am doubting now about https://github.com/ietf-wg-dance/draft-dance-architecture/pull/30/commits/0bd637e256233688002d7056f644fa4ce923f8a9 because I was assuming that the CA would always be learnt from TLSA records.  Checking on TLS 1.3, I found that at least that version makes the CA list optional.

**Comment by mcr** [comment]
Hi, sorry to take so long.
I don't understand why you are removing the definition of Identity provisioning.
I also am uncertain if, in the architecture, we should do IANA allocations.
So I'm going to hand merge everything else.

**Comment by mcr** [comment]
Closed, merged manually. Thank you Rick.

**Pull request closed without merging**
